import leftHand from "./images/left-hand.png";
import rightHand from "./images/right-hand.png";
import humanOne from "./images/image-1.png";
import humanTwo from "./images/image-2.png";
import humanThree from "./images/image-3.png";
import vector from "./images/vector.png";
import vectorOne from "./images/vector-1.png";
import vectorTwo from "./images/vector-2.png";
import vectorThree from "./images/vector-3.png";
import vectorFour from "./images/vector-4.png";
import vectorFive from "./images/vector-5.png";
import vectorSix from "./images/vector-6.png";
import vectorSeven from "./images/vector-7.png";
import vectorEight from "./images/vector-8.png";
import illustration from "./images/illustration.png";
import youtube from "./images/ytb-1.png";
import adLeftHand from "./images/ad-left-hand.png";
import adRightHand from "./images/ad-right-hand.png";
import like from "./images/like.png";
import research from "./images/research.png";
import concept from "./images/concept.png";
import design from "./images/design.png";
import twitter from "./images/twitter.png";
import pinterest from "./images/pinterest.png";

export const leftHandImageUrl = leftHand;
export const rightHandImageUrl = rightHand;
export const adLeftHandImageUrl = adLeftHand;
export const adRightHandImageUrl = adRightHand;
export const humanImageOneUrl = humanOne;
export const humanImageTwoUrl = humanTwo;
export const humanImageThreeUrl = humanThree;
export const vectorUrl = vector;
export const vectorOneUrl = vectorOne;
export const vectorTwoUrl = vectorTwo;
export const vectorThreeUrl = vectorThree;
export const vectorFourUrl = vectorFour;
export const vectorFiveUrl = vectorFive;
export const vectorSixUrl = vectorSix;
export const vectorSevenUrl = vectorSeven;
export const vectorEightUrl = vectorEight;
export const illustrationUrl = illustration;
export const youtubeImageUrl = youtube;
export const likeImageUrl = like;
export const researchImageUrl = research;
export const conceptImageUrl = concept;
export const designImageUrl = design;
export const twitterImageUrl = twitter;
export const pinterestImageUrl = pinterest;
